Repository Sparta-F4T1/Logistics-Server, pull requests merged in 2025-03, with the labels that each got.

#15 [Company] company-service 추가 및 create 구현
  company-service/build.gradle
  company-service/src/main/java/com/logistic/company/CompanyApplication.java
  company-service/src/main/java/com/logistic/company/adaptor/in/web/CompanyWebAdaptor.java
  company-service/src/main/java/com/logistic/company/adaptor/in/web/mapper/CompanyWebMapper.java
  company-service/src/main/java/com/logistic/company/adaptor/in/web/request/CompanyCreateRequest.java
  company-service/src/main/java/com/logistic/company/adaptor/in/web/response/CompanyResponseDto.java
  company-service/src/main/java/com/logistic/company/adaptor/out/client/GpsClientAdaptor.java
  company-service/src/main/java/com/logistic/company/adaptor/out/client/GpsFeignClient.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/AddressValue.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/CompanyEntity.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/TimeStamped.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/mapper/CompanyPersistenceMapper.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/repository/CompanyJpaRepository.java
  company-service/src/main/java/com/logistic/company/adaptor/out/persistence/repository/CompanyPersistenceAdaptor.java
  company-service/src/main/java/com/logistic/company/application/port/in/CompanyUseCase.java
  company-service/src/main/java/com/logistic/company/application/port/in/command/CompanyCreateCommand.java
  company-service/src/main/java/com/logistic/company/application/port/out/CompanyPersistencePort.java
  company-service/src/main/java/com/logistic/company/application/port/out/GpsClientPort.java
  company-service/src/main/java/com/logistic/company/application/service/CompanyService.java
  company-service/src/main/java/com/logistic/company/domain/Company.java
  company-service/src/main/java/com/logistic/company/domain/CompanyType.java
  company-service/src/main/java/com/logistic/company/domain/vo/Address.java
  company-service/src/test/java/com/logistic/company/CompanyApplicationTests.java
  company-service/src/test/java/com/logistic/company/application/service/CompanyServiceTest.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#18 [Product] product-service 추가 및 create 구현
  product-service/build.gradle
  product-service/src/main/java/com/logistic/product/ProductApplication.java
  product-service/src/main/java/com/logistic/product/adaptor/in/web/ProductWebAdaptor.java
  product-service/src/main/java/com/logistic/product/adaptor/in/web/mapper/ProductWebMapper.java
  product-service/src/main/java/com/logistic/product/adaptor/in/web/request/ProductCreateRequest.java
  product-service/src/main/java/com/logistic/product/adaptor/in/web/response/ProductCreateResponse.java
  product-service/src/main/java/com/logistic/product/adaptor/out/client/CompanyClientAdaptor.java
  product-service/src/main/java/com/logistic/product/adaptor/out/client/CompanyFeignClient.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/ProductEntity.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/StockValue.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/TimeStamped.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/mapper/ProductPersistenceMapper.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/repository/ProductJpaRepository.java
  product-service/src/main/java/com/logistic/product/adaptor/out/persistence/repository/ProductPersistenceAdaptor.java
  product-service/src/main/java/com/logistic/product/application/port/in/ProductUseCase.java
  product-service/src/main/java/com/logistic/product/application/port/in/command/ProductCreateCommand.java
  product-service/src/main/java/com/logistic/product/application/port/out/CompanyClientPort.java
  product-service/src/main/java/com/logistic/product/application/port/out/ProductPersistencePort.java
  product-service/src/main/java/com/logistic/product/application/service/ProductService.java
  product-service/src/main/java/com/logistic/product/domain/Product.java
  product-service/src/main/java/com/logistic/product/domain/vo/Stock.java
  product-service/src/test/java/com/logistic/product/ProductApplicationTests.java
  product-service/src/test/java/com/logistic/product/application/service/ProductServiceTest.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#22 [Delivery] delivery-service 모듈 생성 및 Create 구현
  delivery-service/build.gradle
  delivery-service/gradle/wrapper/gradle-wrapper.jar
  delivery-service/src/main/java/com/logistic/delivery/DeliveryApplication.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/in/web/DeliveryController.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/in/web/mapper/DeliveryWebMapper.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/in/web/request/DeliveryCreateRequest.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/in/web/response/DeliveryResponse.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/out/persistence/DeliveryEntity.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/out/persistence/DeliveryPersistenceAdaptor.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/out/persistence/mapper/DeliveryPersistenceMapper.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/out/persistence/repository/DeliveryJpaRepository.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/in/DeliveryUseCase.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/in/command/DeliveryCreateCommand.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/out/DeliveryPersistencePort.java
  delivery-service/src/main/java/com/logistic/delivery/application/service/DeliveryService.java
  delivery-service/src/main/java/com/logistic/delivery/domain/Delivery.java
  delivery-service/src/main/java/com/logistic/delivery/domain/DeliveryStatus.java
  delivery-service/src/test/java/com/logistic/delivery/DeliveryServiceApplicationTests.java
  delivery-service/src/test/java/com/logistic/delivery/application/service/DeliveryServiceTest.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#24 [HUB] hub-service 추가 및 crud 구현
  hub-service/build.gradle
  hub-service/gradle/wrapper/gradle-wrapper.jar
  hub-service/src/main/java/com/logistic/hub/HubServiceApplication.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/HubWebAdaptor.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/mapper/HubWebMapper.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/request/HubCreateRequest.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/request/HubUpdateRequest.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/response/HubCreateResponse.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/response/HubDetailsResponse.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/response/HubHistoryListResponse.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/response/HubHistoryResponse.java
  hub-service/src/main/java/com/logistic/hub/adaptor/in/web/response/PageInfoResponse.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/NaverClientAdaptor.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/AddressValue.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/BaseEntity.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/HubEntity.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/HubJpaRepository.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/HubPersistenceAdaptor.java
  hub-service/src/main/java/com/logistic/hub/adaptor/out/persistence/mapper/HubPersistenceMapper.java
  hub-service/src/main/java/com/logistic/hub/application/port/in/HubUseCase.java
  hub-service/src/main/java/com/logistic/hub/application/port/in/command/HubCreateCommand.java
  hub-service/src/main/java/com/logistic/hub/application/port/in/command/HubUpdateCommand.java
  hub-service/src/main/java/com/logistic/hub/application/port/out/HubPersistencePort.java
  hub-service/src/main/java/com/logistic/hub/application/port/out/NaverClientPort.java
  hub-service/src/main/java/com/logistic/hub/application/service/HubService.java
  hub-service/src/main/java/com/logistic/hub/config/QueryDslConfig.java
  hub-service/src/main/java/com/logistic/hub/domain/Hub.java
  hub-service/src/main/java/com/logistic/hub/domain/HubType.java
  hub-service/src/main/java/com/logistic/hub/domain/command/AddressCommand.java
  hub-service/src/main/java/com/logistic/hub/domain/vo/Address.java
  hub-service/src/test/java/com/logistic/hub/HubServiceApplicationTests.java
  hub-service/src/test/java/com/logistic/hub/application/service/HubServiceTest.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#35 [COMMON] ver.1.0.0
  common-server/src/main/java/com/logistic/common/annotation/Adapter.java
  common-server/src/main/java/com/logistic/common/annotation/WebAdapter.java
  common-server/src/main/java/com/logistic/common/handler/AbstractGlobalExceptionHandler.java
  common-server/src/main/java/com/logistic/common/internal/client/AiInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/CompanyInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/DeliveryInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/DriverInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/GpsInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/HubInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/NotificationInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/OrderInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/ProductInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/RouteInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/UserInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/request/AiClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/AuthClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/CompanyClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/DeliveryClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/DriverClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/GpsClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/HubClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/NotificationClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/OrderClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/ProductClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/RouteClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/request/UserClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/response/AiClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/AuthClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/CompanyClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/DeliveryClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/DriverClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/GpsClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/HubClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/NotificationClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/OrderClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/ProductClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/RouteClientResponse.java
  common-server/src/main/java/com/logistic/common/internal/response/UserClientResponse.java
  common-server/src/main/java/com/logistic/common/passport/model/Passport.java
  common-server/src/main/java/com/logistic/common/passport/model/SessionInfo.java
  common-server/src/main/java/com/logistic/common/passport/model/UserInfo.java
  common-server/src/main/java/com/logistic/common/response/ApiResponse.java
  common-server/src/main/java/com/logistic/common/response/code/CommonCode.java
Labels: ❤️‍🔥 Feat, 🔥 Refactor

#33 [Order] Order Create 구현
  order-service/build.gradle
  order-service/src/main/java/com/logistic/order/OrderServiceApplication.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/OrderWebAdapter.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/mapper/OrderWebMapper.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/request/OrderCreateRequest.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/request/OrderProductCreateRequest.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/response/OrderCreateResponse.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/BaseEntity.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/OrderEntity.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/OrderPersistenceAdapter.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/OrderProductValue.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/mapper/OrderPersistenceMapper.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/repository/OrderJpaRepository.java
  order-service/src/main/java/com/logistic/order/application/port/OrderPersistencePort.java
  order-service/src/main/java/com/logistic/order/application/port/in/OrderUseCase.java
  order-service/src/main/java/com/logistic/order/application/port/in/command/OrderCreateCommand.java
  order-service/src/main/java/com/logistic/order/application/port/in/command/OrderProductCreateCommand.java
  order-service/src/main/java/com/logistic/order/application/service/OrderService.java
  order-service/src/main/java/com/logistic/order/domain/Order.java
  order-service/src/main/java/com/logistic/order/domain/OrderProduct.java
  order-service/src/main/java/com/logistic/order/domain/OrderStatus.java
  order-service/src/test/java/com/logistic/order/OrderServiceApplicationTests.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#37 [Delivery] Delivery-Service-Create 수정
  delivery-service/build.gradle
  delivery-service/src/main/java/com/logistic/delivery/DeliveryApplication.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/in/web/DeliveryWebAdapter.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/in/web/mapper/DeliveryWebMapper.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/in/web/request/DeliveryCreateRequest.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/in/web/response/DeliveryResponse.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/client/DeliveryClientAdapter.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/client/DriverFeignClient.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/client/HubFeignClient.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/DeliveryEntity.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/HubDeliveryHistoryValue.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/mapper/DeliveryPersistenceMapper.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/repository/DeliveryJpaRepository.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/repository/DeliveryPersistenceAdapter.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/value/DistanceValue.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/value/SequenceValue.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/persistence/value/TimeValue.java
  delivery-service/src/main/java/com/logistic/delivery/adaptor/out/persistence/mapper/DeliveryPersistenceMapper.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/in/command/DeliveryCreateCommand.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/out/DeliveryInternalPort.java
  delivery-service/src/main/java/com/logistic/delivery/application/port/out/DeliveryPersistencePort.java
  delivery-service/src/main/java/com/logistic/delivery/application/service/DeliveryService.java
  delivery-service/src/main/java/com/logistic/delivery/domain/Delivery.java
  delivery-service/src/main/java/com/logistic/delivery/domain/HubDeliveryHistory.java
  delivery-service/src/main/java/com/logistic/delivery/domain/vo/Distance.java
  delivery-service/src/main/java/com/logistic/delivery/domain/vo/Sequence.java
  delivery-service/src/main/java/com/logistic/delivery/domain/vo/Time.java
  delivery-service/src/test/java/com/logistic/delivery/application/service/DeliveryServiceTest.java
Labels: 🕹️ Chore, ❤️‍🔥 Feat, ⚒️ Fix

#42 [Common] ver.1.1.0
  common-server/src/main/java/com/logistic/common/internal/client/CompanyInternalClient.java
  common-server/src/main/java/com/logistic/common/passport/PassportWebConfig.java
  common-server/src/main/java/com/logistic/common/passport/annotation/WithPassport.java
  common-server/src/main/java/com/logistic/common/passport/constant/PassportConstant.java
  common-server/src/main/java/com/logistic/common/passport/filter/PassportFilter.java
  common-server/src/main/java/com/logistic/common/passport/model/Passport.java
  common-server/src/main/java/com/logistic/common/passport/model/RoleType.java
  common-server/src/main/java/com/logistic/common/passport/model/SessionInfo.java
  common-server/src/main/java/com/logistic/common/passport/model/UserInfo.java
  common-server/src/main/java/com/logistic/common/passport/resolver/PassportArgumentResolver.java
  common-server/src/main/java/com/logistic/common/passport/util/PassportUtils.java
Labels: ❤️‍🔥 Feat

#44 [Order] Order Read, Update, Delete
  order-service/build.gradle
  order-service/src/main/java/com/logistic/order/adapter/in/handler/GlobalExceptionHandler.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/OrderQueryAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/OrderWebAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/mapper/OrderWebMapper.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/request/CreateOrderRequest.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/request/SearchOrderRequest.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/response/CreateOrderResponse.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/response/FindOrderResponse.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/response/SearchOrderResponse.java
  order-service/src/main/java/com/logistic/order/adapter/in/web/response/UpdateOrderResponse.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/BaseEntity.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/OrderEntity.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/OrderPersistenceAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/OrderProductValue.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/QueryDslConfig.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/mapper/OrderPersistenceMapper.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/repository/OrderJpaRepository.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/repository/OrderQueryDslRepository.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/OrderWebAdapter.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/mapper/OrderWebMapper.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/request/OrderCreateRequest.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/request/OrderProductCreateRequest.java
  order-service/src/main/java/com/logistic/order/adaptor/in/web/response/OrderCreateResponse.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/OrderPersistenceAdapter.java
  order-service/src/main/java/com/logistic/order/adaptor/out/persistence/OrderProductValue.java
  order-service/src/main/java/com/logistic/order/application/port/OrderPersistencePort.java
  order-service/src/main/java/com/logistic/order/application/port/in/OrderQueryUseCase.java
  order-service/src/main/java/com/logistic/order/application/port/in/OrderUseCase.java
  order-service/src/main/java/com/logistic/order/application/port/in/command/CreateOrderCommand.java
  order-service/src/main/java/com/logistic/order/application/port/in/query/SearchOrderQuery.java
  order-service/src/main/java/com/logistic/order/application/service/OrderQueryService.java
  order-service/src/main/java/com/logistic/order/application/service/OrderService.java
  order-service/src/main/java/com/logistic/order/domain/BaseException.java
  order-service/src/main/java/com/logistic/order/domain/Order.java
  order-service/src/main/java/com/logistic/order/domain/OrderException.java
  order-service/src/main/java/com/logistic/order/domain/vo/OrderProduct.java
Labels: ❤️‍🔥 Feat

#43 [Auth] 로그인, 로그아웃, 리프레쉬 토큰 발급 기능 구현
  auth-service/build.gradle
  auth-service/gradle/wrapper/gradle-wrapper.jar
  auth-service/src/main/java/com/logistic/auth/AuthServiceApplication.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/exception/AuthGlobalExceptionHandler.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/AuthWebAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/mapper/AuthWebMapper.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/request/LoginRequest.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/request/LogoutRequest.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/request/RefreshTokenRequest.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/response/LoginResponse.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/response/LogoutResponse.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/response/RefreshTokenResponse.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/AuthPersistenceAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/mapper/AuthPersistenceMapper.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/repository/TokenRedisRepository.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/encode/config/PasswordEncodeConfig.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/AuthJwtAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/config/JwtConfig.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/mapper/AuthJwtMapper.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/util/AbstractJwtSupport.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/util/JwtProvider.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/util/JwtValidator.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/uuid/UuidGeneratorAdapter.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/AuthCommandUseCase.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/command/LoginCommand.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/command/LogoutCommand.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/command/RefreshCommand.java
  auth-service/src/main/java/com/logistic/auth/application/port/out/persistence/AuthPersistencePort.java
  auth-service/src/main/java/com/logistic/auth/application/port/out/support/jwt/AuthJwtPort.java
  auth-service/src/main/java/com/logistic/auth/application/port/out/support/uuid/IdGeneratorPort.java
  auth-service/src/main/java/com/logistic/auth/application/service/AuthCommandService.java
  auth-service/src/main/java/com/logistic/auth/domain/TokenPair.java
  auth-service/src/main/java/com/logistic/auth/domain/User.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/AuthServiceErrorCode.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/AuthServiceException.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/ErrorCode.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/JwtExpiredException.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/JwtParsingException.java
  auth-service/src/main/java/com/logistic/auth/domain/service/TokenValidationResult.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/Password.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenClaims.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenCredential.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenId.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenType.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/UserId.java
  auth-service/src/test/java/com/logistic/auth/AuthServiceApplicationTests.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#46 [Gateway] API Gateway 설정 및 필터 기능 구현
  api-gateway/build.gradle
  api-gateway/gradle/wrapper/gradle-wrapper.jar
  api-gateway/src/main/java/com/logistic/gateway/ApiGatewayApplication.java
  api-gateway/src/main/java/com/logistic/gateway/client/AuthServiceClient.java
  api-gateway/src/main/java/com/logistic/gateway/config/GatewayConfig.java
  api-gateway/src/main/java/com/logistic/gateway/config/WebClientConfig.java
  api-gateway/src/main/java/com/logistic/gateway/constants/AppConstants.java
  api-gateway/src/main/java/com/logistic/gateway/filter/auth/AuthenticationFilter.java
  api-gateway/src/main/java/com/logistic/gateway/filter/auth/AuthorizationFilter.java
  api-gateway/src/main/java/com/logistic/gateway/filter/auth/TokenExtractorFilter.java
  api-gateway/src/main/java/com/logistic/gateway/filter/logging/GatewayLoggingFilter.java
  api-gateway/src/test/java/com/logistic/gateway/ApiGatewayApplicationTests.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/entity/UserEntity.java
  common-server/src/main/java/com/logistic/common/internal/response/AuthClientResponse.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#53 [GPS] gps-service 추가
  common-server/src/main/java/com/logistic/common/internal/client/GpsInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/request/GpsClientRequest.java
  common-server/src/main/java/com/logistic/common/internal/response/GpsClientResponse.java
  gps-service/build.gradle
  gps-service/gradle/wrapper/gradle-wrapper.jar
  gps-service/src/main/java/com/logistic/gps/GpsServiceApplication.java
  gps-service/src/main/java/com/logistic/gps/adapter/in/internal/GpsInternalAdaptor.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/GpsExternalAdaptor.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/NaverFeignClient.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/NaverDirectionResponse.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/NaverGeoAddressDetail.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/NaverGeoResponse.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/RouteDto.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/RouteSummaryDto.java
  gps-service/src/main/java/com/logistic/gps/adapter/out/external/response/TraoptimalDto.java
  gps-service/src/main/java/com/logistic/gps/application/port/in/GpsUseCase.java
  gps-service/src/main/java/com/logistic/gps/application/port/in/command/GpsDistanceCommand.java
  gps-service/src/main/java/com/logistic/gps/application/port/in/command/GpsInfoCommand.java
  gps-service/src/main/java/com/logistic/gps/application/port/out/GpsExternalPort.java
  gps-service/src/main/java/com/logistic/gps/application/service/GpsService.java
  gps-service/src/main/java/com/logistic/gps/domain/Direction.java
  gps-service/src/main/java/com/logistic/gps/domain/Gps.java
  gps-service/src/test/java/com/logistic/gps/GpsServiceApplicationTests.java
  hub-service/src/main/java/com/logistic/hub/application/service/RouteService.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#47 [User] 사용자 CRUD 구현
  user-service/build.gradle
  user-service/src/main/java/com/logistic/user/UserApplication.java
  user-service/src/main/java/com/logistic/user/adapter/in/exception/handler/UserGlobalExceptionHandler.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/UserWebAdapter.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/mapper/UserWebMapper.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/request/RegisterUserRequest.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/request/UpdateUserRequest.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/request/UpdateUserStatusRequest.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/response/FindUserResponse.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/response/UpdateUserResponse.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/response/UpdateUserStatusResponse.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/UserPersistenceAdapter.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/config/JpaConfig.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/config/PassportAuditorAware.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/config/QueryDslConfig.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/entity/BaseEntity.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/entity/UserEntity.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/entity/UserRoleValue.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/mapper/UserPersistenceMapper.java
  user-service/src/main/java/com/logistic/user/adapter/out/persistence/repository/UserJapRepository.java
  user-service/src/main/java/com/logistic/user/adapter/out/support/passwordencoder/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/logistic/user/adaptor/in/web/UserWebAdaptor.java
  user-service/src/main/java/com/logistic/user/adaptor/in/web/request/TestRequest.java
  user-service/src/main/java/com/logistic/user/adaptor/out/persistence/BaseEntity.java
  user-service/src/main/java/com/logistic/user/adaptor/out/persistence/UserEntity.java
  user-service/src/main/java/com/logistic/user/adaptor/out/persistence/UserJpaRepository.java
  user-service/src/main/java/com/logistic/user/adaptor/out/persistence/UserMapper.java
  user-service/src/main/java/com/logistic/user/adaptor/out/persistence/UserPersistenceAdaptor.java
  user-service/src/main/java/com/logistic/user/application/port/in/UserCommandUseCase.java
  user-service/src/main/java/com/logistic/user/application/port/in/UserQueryUseCase.java
  user-service/src/main/java/com/logistic/user/application/port/in/UserUseCase.java
  user-service/src/main/java/com/logistic/user/application/port/in/command/DeleteUserCommand.java
  user-service/src/main/java/com/logistic/user/application/port/in/command/RegisterUserCommand.java
  user-service/src/main/java/com/logistic/user/application/port/in/command/TestCommand.java
  user-service/src/main/java/com/logistic/user/application/port/in/command/UpdateUserCommand.java
  user-service/src/main/java/com/logistic/user/application/port/in/command/UpdateUserStatusCommand.java
  user-service/src/main/java/com/logistic/user/application/port/in/query/FindUserQuery.java
  user-service/src/main/java/com/logistic/user/application/port/out/UserPersistencePort.java
  user-service/src/main/java/com/logistic/user/application/port/out/persistence/UserPersistencePort.java
  user-service/src/main/java/com/logistic/user/application/service/UserCommandService.java
  user-service/src/main/java/com/logistic/user/application/service/UserQueryService.java
  user-service/src/main/java/com/logistic/user/application/service/UserService.java
  user-service/src/main/java/com/logistic/user/domain/User.java
  user-service/src/main/java/com/logistic/user/domain/UserRole.java
  user-service/src/main/java/com/logistic/user/domain/command/UserForUpdate.java
  user-service/src/main/java/com/logistic/user/domain/exception/ErrorCode.java
  user-service/src/main/java/com/logistic/user/domain/exception/UserServiceErrorCode.java
  user-service/src/main/java/com/logistic/user/domain/exception/UserServiceException.java
  user-service/src/main/java/com/logistic/user/domain/vo/Email.java
  user-service/src/main/java/com/logistic/user/domain/vo/Name.java
  user-service/src/main/java/com/logistic/user/domain/vo/Password.java
  user-service/src/main/java/com/logistic/user/domain/vo/UserId.java
  user-service/src/main/java/com/logistic/user/domain/vo/UserRole.java
  user-service/src/main/java/com/logistic/user/domain/vo/UserStatus.java
  user-service/src/test/java/com/logistic/user/adapter/in/web/UserWebAdapterRegisterTest.java
  user-service/src/test/java/com/logistic/user/application/service/UserCommandServiceRegisterTest.java
  user-service/src/test/java/com/logistic/user/domain/vo/ValueObjectsTest.java
Labels: ❤️‍🔥 Feat

#60 [Auth] 인증 및 권한 부여, Passport 발급 구현
  api-gateway/build.gradle
  auth-service/build.gradle
  auth-service/src/main/java/com/logistic/auth/AuthServiceApplication.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/exception/AuthGlobalExceptionHandler.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/internal/AuthServiceAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/internal/mapper/AuthServiceFactory.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/internal/mapper/AuthServiceMapper.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/AuthWebAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/request/LogoutRequest.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/request/RefreshTokenRequest.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/AuthPersistenceAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/config/JpaConfig.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/config/PassportAuditorAware.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/entity/UserEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/mapper/AuthPersistenceMapper.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/BaseEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/PermissionEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/RoleEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/RolePermissionEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/UserEntity.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/model/vo/PasswordValue.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/repository/PassportRedisRepository.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/persistence/repository/UserJpaRepository.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/jwt/util/JwtValidator.java
  auth-service/src/main/java/com/logistic/auth/adapter/out/support/resource/HttpResourceExtractorAdapter.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/AuthenticationCommandUseCase.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/AuthenticationQueryUseCase.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/AuthorizationCommandUseCase.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/command/IssuePassportCommand.java
  auth-service/src/main/java/com/logistic/auth/application/port/in/query/VerifyTokenQuery.java
  auth-service/src/main/java/com/logistic/auth/application/port/out/persistence/AuthPersistencePort.java
  auth-service/src/main/java/com/logistic/auth/application/port/out/support/resource/ResourceExtractorPort.java
  auth-service/src/main/java/com/logistic/auth/application/service/AuthenticationCommandService.java
  auth-service/src/main/java/com/logistic/auth/application/service/AuthenticationQueryService.java
  auth-service/src/main/java/com/logistic/auth/application/service/AuthorizationCommandService.java
  auth-service/src/main/java/com/logistic/auth/domain/Passport.java
  auth-service/src/main/java/com/logistic/auth/domain/Permission.java
  auth-service/src/main/java/com/logistic/auth/domain/Role.java
  auth-service/src/main/java/com/logistic/auth/domain/TokenPair.java
  auth-service/src/main/java/com/logistic/auth/domain/User.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/AuthServiceErrorCode.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/AuthServiceException.java
  auth-service/src/main/java/com/logistic/auth/domain/exception/JwtParsingException.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/AccessScope.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/ActionType.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/Password.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/PermissionId.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/ResourceType.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/RoleId.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/RoleName.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/RoleType.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenClaims.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenCredential.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/TokenId.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/UserId.java
  auth-service/src/main/java/com/logistic/auth/domain/vo/UserInfo.java
  auth-service/src/main/resources/sql/role_permission_sql.sql
  user-service/build.gradle
  user-service/src/main/java/com/logistic/user/UserApplication.java
Labels: ❤️‍🔥 Feat

#63 [Service Registry] Eureka 서비스 등록
  service-registry/build.gradle
  service-registry/gradle/wrapper/gradle-wrapper.jar
  service-registry/src/main/java/com/logistic/serviceregistry/ServiceRegistryApplication.java
  service-registry/src/test/java/com/logistic/serviceregistry/ServiceRegistryApplicationTests.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#61 [AI] ai-service 구현
  ai-service/build.gradle
  ai-service/gradle/wrapper/gradle-wrapper.jar
  ai-service/src/main/java/com/logistic/ai/AiApplication.java
  ai-service/src/main/java/com/logistic/ai/adapter/in/internal/AiServiceAdapter.java
  ai-service/src/main/java/com/logistic/ai/adapter/in/internal/mapper/AiServiceMapper.java
  ai-service/src/main/java/com/logistic/ai/adapter/in/internal/parser/DateTimeParser.java
  ai-service/src/main/java/com/logistic/ai/adapter/in/internal/request/GetDeadLineRequest.java
  ai-service/src/main/java/com/logistic/ai/adapter/in/internal/response/GetDeadLineResponse.java
  ai-service/src/main/java/com/logistic/ai/adapter/out/external/ai/ChatGPTAdapter.java
  ai-service/src/main/java/com/logistic/ai/adapter/out/external/ai/ChatGPTConfig.java
  ai-service/src/main/java/com/logistic/ai/adapter/out/external/ai/dto/GPTRequest.java
  ai-service/src/main/java/com/logistic/ai/adapter/out/external/ai/dto/GPTResponse.java
  ai-service/src/main/java/com/logistic/ai/adapter/out/external/ai/dto/Message.java
  ai-service/src/main/java/com/logistic/ai/application/port/in/AiUseCase.java
  ai-service/src/main/java/com/logistic/ai/application/port/in/command/GetDeadLineCommand.java
  ai-service/src/main/java/com/logistic/ai/application/port/out/ChatGPTPort.java
  ai-service/src/main/java/com/logistic/ai/application/service/AiService.java
  ai-service/src/test/java/com/logistic/ai/AiApplicationTests.java
  settings.gradle
Labels: ❤️‍🔥 Feat

#69 [Product] Product 예외처리 및 분산락 구현
  product-service/build.gradle
  product-service/src/main/java/com/logistic/product/ProductApplication.java
  product-service/src/main/java/com/logistic/product/adapter/in/exception/GlobalExceptionHandler.java
  product-service/src/main/java/com/logistic/product/adapter/in/external/web/ProductWebAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/in/external/web/mapper/ProductWebMapper.java
  product-service/src/main/java/com/logistic/product/adapter/in/external/web/response/CommandProductResponse.java
  product-service/src/main/java/com/logistic/product/adapter/in/external/web/response/QueryProductResponse.java
  product-service/src/main/java/com/logistic/product/adapter/in/internal/ProductServiceAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/in/internal/mapper/ProductInternalMapper.java
  product-service/src/main/java/com/logistic/product/adapter/out/internal/ProductInternalAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/internal/client/HubFeignClient.java
  product-service/src/main/java/com/logistic/product/adapter/out/internal/mapper/ProductClientMapper.java
  product-service/src/main/java/com/logistic/product/adapter/out/lock/ProductLockAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/lock/config/RedisConfig.java
  product-service/src/main/java/com/logistic/product/adapter/out/lock/util/RedisKeyFactory.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/ProductCommandPersistenceAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/ProductQueryPersistenceAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/mapper/ProductPersistenceMapper.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/model/ProductEntity.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/model/vo/ProductInfoValue.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/model/vo/StockVo.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/repository/ProductQueryDslRepository.java
  product-service/src/main/java/com/logistic/product/application/port/in/ProductCommandUseCase.java
  product-service/src/main/java/com/logistic/product/application/port/in/command/CreateProductCommand.java
  product-service/src/main/java/com/logistic/product/application/port/in/command/DecreaseStockCommand.java
  product-service/src/main/java/com/logistic/product/application/port/in/command/UpdateStockCommand.java
  product-service/src/main/java/com/logistic/product/application/port/out/ProductCommandPersistencePort.java
  product-service/src/main/java/com/logistic/product/application/port/out/ProductInternalPort.java
  product-service/src/main/java/com/logistic/product/application/port/out/ProductLockPort.java
  product-service/src/main/java/com/logistic/product/application/port/out/ProductQueryPersistencePort.java
  product-service/src/main/java/com/logistic/product/application/service/ProductCommandService.java
  product-service/src/main/java/com/logistic/product/application/service/ProductEventListener.java
  product-service/src/main/java/com/logistic/product/application/service/ProductQueryService.java
  product-service/src/main/java/com/logistic/product/application/service/dto/CompanyInfo.java
  product-service/src/main/java/com/logistic/product/domain/Product.java
  product-service/src/main/java/com/logistic/product/domain/ProductPolicyService.java
  product-service/src/main/java/com/logistic/product/domain/command/ProductForCreate.java
  product-service/src/main/java/com/logistic/product/domain/event/StockLockReleaseEvent.java
  product-service/src/main/java/com/logistic/product/domain/exception/CustomBadRequestException.java
  product-service/src/main/java/com/logistic/product/domain/exception/CustomForbiddenException.java
  product-service/src/main/java/com/logistic/product/domain/exception/CustomNotFoundException.java
  product-service/src/main/java/com/logistic/product/domain/exception/DomainErrorCode.java
  product-service/src/main/java/com/logistic/product/domain/exception/DomainException.java
  product-service/src/main/java/com/logistic/product/domain/exception/ErrorCode.java
  product-service/src/main/java/com/logistic/product/domain/vo/Company.java
  product-service/src/main/java/com/logistic/product/domain/vo/Hub.java
  product-service/src/main/java/com/logistic/product/domain/vo/ProductInfo.java
  product-service/src/main/java/com/logistic/product/domain/vo/Stock.java
  product-service/src/test/java/com/logistic/product/application/service/ProductQueryServiceTest.java
  product-service/src/test/java/com/logistic/product/application/service/ProductServiceTest.java
Labels: ❤️‍🔥 Feat, 🔥 Refactor

#82 [Driver] infra 구현
  driver-service/src/main/java/com/logistic/driver/adapter/out/internal/DriverInternalAdapter.java
  driver-service/src/main/java/com/logistic/driver/adapter/out/message/DriverMessageAdapter.java
Labels: ❤️‍🔥 Feat

#84 [Swagger] API 문서화 적용
  auth-service/build.gradle
  auth-service/src/main/java/com/logistic/auth/adapter/in/internal/AuthServiceAdapter.java
  auth-service/src/main/java/com/logistic/auth/adapter/in/web/config/SwaggerConfig.java
  company-service/build.gradle
  company-service/src/main/java/com/logistic/company/adapter/in/external/web/config/SwaggerConfig.java
  company-service/src/main/java/com/logistic/company/adapter/in/internal/CompanyServiceAdapter.java
  delivery-service/build.gradle
  delivery-service/src/main/java/com/logistic/delivery/adapter/in/web/config/SwaggerConfig.java
  driver-service/build.gradle
  driver-service/src/main/java/com/logistic/driver/adapter/in/external/web/config/SwaggerConfig.java
  driver-service/src/main/java/com/logistic/driver/adapter/in/internal/DriverServiceAdapter.java
  gps-service/build.gradle
  hub-service/build.gradle
  hub-service/src/main/java/com/logistic/hub/adapter/in/internal/HubClientAdaptor.java
  hub-service/src/main/java/com/logistic/hub/adapter/in/internal/RouteClientAdaptor.java
  hub-service/src/main/java/com/logistic/hub/config/SwaggerConfig.java
  order-service/build.gradle
  order-service/src/main/java/com/logistic/order/adapter/in/external/web/config/SwaggerConfig.java
  order-service/src/main/java/com/logistic/order/adapter/in/internal/OrderServiceAdapter.java
  product-service/build.gradle
  product-service/src/main/java/com/logistic/product/adapter/in/external/web/config/SwaggerConfig.java
  product-service/src/main/java/com/logistic/product/adapter/in/internal/ProductServiceAdapter.java
  user-service/src/main/java/com/logistic/user/adapter/in/web/config/SwaggerConfig.java
Labels: ❤️‍🔥 Feat

#85 Feat: 주문 상세 정보 조회 및 notification에 전달
  order-service/src/main/java/com/logistic/order/adapter/out/internal/OrderInternalAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/out/internal/client/ProductFeignClient.java
  order-service/src/main/java/com/logistic/order/adapter/out/internal/mapper/OrderClientMapper.java
  order-service/src/main/java/com/logistic/order/adapter/out/message/MessageAdapter.java
  order-service/src/main/java/com/logistic/order/application/port/out/MessagePort.java
  order-service/src/main/java/com/logistic/order/application/port/out/OrderInternalPort.java
  order-service/src/main/java/com/logistic/order/application/service/OrderService.java
  order-service/src/main/java/com/logistic/order/application/service/dto/UserDto.java
  order-service/src/main/java/com/logistic/order/domain/Order.java
  order-service/src/main/java/com/logistic/order/domain/vo/Company.java
  order-service/src/main/java/com/logistic/order/domain/vo/OrderProduct.java
  order-service/src/main/java/com/logistic/order/domain/vo/Product.java
  order-service/src/main/java/com/logistic/order/domain/vo/User.java
Labels: ❤️‍🔥 Feat

#86 [Order] 배송알림에 필요한 데이터 추가 및 주문 취소 메시지 추가
  common-server/src/main/java/com/logistic/common/internal/client/CompanyInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/HubInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/client/UserInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/message/CancelOrderEvent.java
  common-server/src/main/java/com/logistic/common/internal/message/CreateOrderEvent.java
  order-service/src/main/java/com/logistic/order/adapter/in/external/web/OrderWebAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/out/internal/mapper/OrderClientMapper.java
  order-service/src/main/java/com/logistic/order/adapter/out/message/MessageAdapter.java
  order-service/src/main/java/com/logistic/order/adapter/out/message/config/MessagingQueueConfig.java
  order-service/src/main/java/com/logistic/order/application/port/out/MessagePort.java
  order-service/src/main/java/com/logistic/order/application/service/OrderService.java
Labels: ❤️‍🔥 Feat

#88 [Product] 상품 분산락 수정 및 코드 리팩토링
  common-server/src/main/java/com/logistic/common/internal/message/DeleteCompanyEvent.java
  product-service/src/main/java/com/logistic/product/adapter/in/external/message/ProductEventAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/lock/ProductLockAdapter.java
  product-service/src/main/java/com/logistic/product/adapter/out/persistence/mapper/ProductPersistenceMapper.java
  product-service/src/main/java/com/logistic/product/application/service/ProductCommandService.java
  product-service/src/main/java/com/logistic/product/application/service/ProductEventListener.java
  product-service/src/test/java/com/logistic/product/application/service/ProductServiceTest.java
Labels: ❤️‍🔥 Feat, 🔥 Refactor

#90 [Docker] 도커 컴포즈 추가 및 실행을 위한 코드 수정
  .gitignore
  ai-service/Dockerfile
  ai-service/src/main/resources/application-prod.yml
  ai-service/src/main/resources/application.yml
  api-gateway/Dockerfile
  api-gateway/src/main/resources/application-prod.yml
  api-gateway/src/main/resources/application.yml
  auth-service/Dockerfile
  auth-service/src/main/resources/application-prod.yml
  auth-service/src/main/resources/application.yml
  common-server/build.gradle
  common-server/src/test/java/com/logistic/common/CommonApplicationTests.java
  company-service/Dockerfile
  company-service/src/main/resources/application-prod.yml
  company-service/src/main/resources/application.yml
  delivery-service/Dockerfile
  delivery-service/build.gradle
  delivery-service/src/main/resources/application-prod.yml
  delivery-service/src/main/resources/application.yml
  docker-compose.yml
  driver-service/Dockerfile
  driver-service/src/main/resources/application-prod.yml
  driver-service/src/main/resources/application.yml
  gps-service/Dockerfile
  gps-service/src/main/resources/application-prod.yml
  gps-service/src/main/resources/application.yml
  hub-service/Dockerfile
  hub-service/src/main/resources/application-prod.yml
  hub-service/src/main/resources/application.yml
  notification-service/Dockerfile
  notification-service/build.gradle
  notification-service/src/main/resources/application-prod.yml
  notification-service/src/main/resources/application.yml
  order-service/Dockerfile
  order-service/src/main/java/com/logistic/order/adapter/in/external/web/mapper/OrderWebMapper.java
  order-service/src/main/java/com/logistic/order/adapter/in/external/web/response/CreateOrderResponse.java
  order-service/src/main/java/com/logistic/order/adapter/in/internal/mapper/OrderInternalMapper.java
  order-service/src/main/java/com/logistic/order/adapter/out/persistence/mapper/OrderPersistenceMapper.java
  order-service/src/main/java/com/logistic/order/domain/Order.java
  order-service/src/main/resources/application-prod.yml
  order-service/src/main/resources/application.yml
  product-service/Dockerfile
  product-service/src/main/resources/application-prod.yml
  product-service/src/main/resources/application.yml
  service-registry/Dockerfile
  service-registry/src/main/resources/application-prod.yml
  service-registry/src/main/resources/application.yml
  service-registry/src/test/java/com/logistic/serviceregistry/ServiceRegistryApplicationTests.java
  user-service/Dockerfile
  user-service/src/main/java/com/logistic/user/adapter/in/internal/UserServiceAdapter.java
  user-service/src/main/resources/application-prod.yml
  user-service/src/main/resources/application.yml
Labels: ❤️‍🔥 Feat

#91 [Monitoring] Prometheus 및 Grafana 추가
  ai-service/build.gradle
  ai-service/src/main/resources/application-prod.yml
  api-gateway/build.gradle
  api-gateway/src/main/resources/application-prod.yml
  auth-service/build.gradle
  auth-service/src/main/resources/application-prod.yml
  company-service/build.gradle
  company-service/src/main/resources/application-prod.yml
  delivery-service/build.gradle
  delivery-service/src/main/resources/application-prod.yml
  docker-compose.yml
  driver-service/build.gradle
  driver-service/src/main/resources/application-prod.yml
  gps-service/build.gradle
  gps-service/src/main/resources/application-prod.yml
  hub-service/build.gradle
  hub-service/src/main/resources/application-prod.yml
  notification-service/build.gradle
  notification-service/src/main/resources/application-prod.yml
  order-service/build.gradle
  order-service/src/main/resources/application-prod.yml
  product-service/build.gradle
  product-service/src/main/resources/application-prod.yml
  prometheus/prometheus.yml
  service-registry/build.gradle
  service-registry/src/main/resources/application-prod.yml
  user-service/build.gradle
  user-service/src/main/resources/application-prod.yml
Labels: 🕹️ Chore

#93 [Fix] 주문 생성 이벤트 컨슘 후 배송 생성 로직 수정
  common-server/src/main/java/com/logistic/common/internal/client/RouteInternalClient.java
  common-server/src/main/java/com/logistic/common/internal/request/RouteClientRequest.java
  company-service/src/main/java/com/logistic/company/adapter/in/internal/mapper/CompanyServiceMapper.java
  delivery-service/src/main/java/com/logistic/delivery/DeliveryApplication.java
  delivery-service/src/main/java/com/logistic/delivery/adapter/out/client/DeliveryClientAdapter.java
  hub-service/src/main/java/com/logistic/hub/adapter/in/internal/RouteClientAdaptor.java
  hub-service/src/main/java/com/logistic/hub/application/service/RouteService.java
  order-service/src/main/java/com/logistic/order/application/service/OrderService.java
Labels: ❤️‍🔥 Feat

#95 [Log] ELK 스택 로깅 시스템 구축
  ai-service/build.gradle
  ai-service/src/main/resources/application.yml
  ai-service/src/main/resources/logback-dev.xml
  ai-service/src/main/resources/logback-prod.xml
  api-gateway/build.gradle
  api-gateway/src/main/java/com/logistic/gateway/config/ReactiveTracingConfig.java
  api-gateway/src/main/java/com/logistic/gateway/config/TraceGatewayFilterConfig.java
  api-gateway/src/main/java/com/logistic/gateway/config/WebClientConfig.java
  api-gateway/src/main/java/com/logistic/gateway/constants/AppConstants.java
  api-gateway/src/main/resources/application.yml
  api-gateway/src/main/resources/logback-dev.xml
  api-gateway/src/main/resources/logback-prod.xml
  auth-service/build.gradle
  auth-service/src/main/resources/application.yml
  auth-service/src/main/resources/logback-dev.xml
  auth-service/src/main/resources/logback-prod.xml
  company-service/build.gradle
  company-service/src/main/resources/application.yml
  company-service/src/main/resources/logback-dev.xml
  company-service/src/main/resources/logback-prod.xml
  config-server/build.gradle
  config-server/src/main/resources/application.yml
  delivery-service/build.gradle
  delivery-service/src/main/resources/application.yml
  delivery-service/src/main/resources/logback-dev.xml
  delivery-service/src/main/resources/logback-prod.xml
  docker-compose.yml
  driver-service/build.gradle
  driver-service/src/main/resources/application.yml
  driver-service/src/main/resources/logback-dev.xml
  driver-service/src/main/resources/logback-prod.xml
  gps-service/build.gradle
  gps-service/src/main/resources/application.yml
  gps-service/src/main/resources/logback-dev.xml
  gps-service/src/main/resources/logback-prod.xml
  hub-service/build.gradle
  hub-service/src/main/resources/application.yml
  hub-service/src/main/resources/logback-dev.xml
  hub-service/src/main/resources/logback-prod.xml
  logstash.conf
  notification-service/src/main/resources/application.yml
  notification-service/src/main/resources/logback-dev.xml
  notification-service/src/main/resources/logback-prod.xml
  order-service/build.gradle
  order-service/src/main/resources/application.yml
  order-service/src/main/resources/logback-dev.xml
  order-service/src/main/resources/logback-prod.xml
  product-service/build.gradle
  product-service/src/main/resources/application.yml
  product-service/src/main/resources/logback-dev.xml
  product-service/src/main/resources/logback-prod.xml
  user-service/build.gradle
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/logback-dev.xml
  user-service/src/main/resources/logback-prod.xml
Labels: ❤️‍🔥 Feat
